[package]
name = "firecracker-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
rustix = { version = "1.1.4", features = ["fs"] }
sha2 = "0.10.9"
socket2 = { version = "0.6.5", features = ["all"] }

[dev-dependencies]
tempfile = "3.27.0"
