[package]
name = "capfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
authority-core = { path = "../authority-core" }
fuser = { version = "0.18.0", default-features = false }
rustix = { version = "1.1.4", features = ["fs"] }

[dev-dependencies]
tempfile = "3.27.0"
